### ISSUE TITLE
Give user option to overwrite the report in a particular directory if it exists already

### ISSUE THREAD

**Issue by sethsec** [mikehacksthings/jast#2]
I ran a report without headers, and then I wanted to run it with --headers and have it overwrite whatever was there before hand. But I had to either write it to a new path or delete the previous folder.

Would be nice if jast asked me whether i wanted to overwrite or exit.

Just a thought. not a big issue.

**Comment by mikehacksthings** [comment]
Thanks for the suggestion, I will definitely implement this. Stay tuned!

**Comment by mikehacksthings** [comment]
I implemented the enhancement in branch issue_02, please check this out and let me know if matches your suggestion. If so, I'll merge over.

**Comment by mikehacksthings** [comment]
As of 0.3.1, you will be prompted to overwrite the report if you specify the same directory.
